apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls
  namespace: harbor
spec:
  secretName: harbor-tls
  issuerRef:
    name: letsencrypt-production   # 或 letsencrypt-production（前提要外網可達）
    kind: ClusterIssuer
  dnsNames:
    - dong-harbor.genai.nchc.org.tw

